backend:
  name: git-gateway
<<<<<<< HEAD
  branch: main 
=======
  branch: master 
>>>>>>> d94b9268 (Initial commit)
media_folder: "public/assets/"
public_folder: "/assets/"
collections:
  - name: "blog" 
    label: "Blog" 
    folder: "src/work" 
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields:
      - {label: "Title", name: "title", widget: "string" }
      - {label: "Descrition", name: "titleDescription", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", default: "all" }
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Image Caption", name: "imageAlt", widget: "string"}
      - {label: "body", name: "body", widget: "markdown"}
<<<<<<< HEAD
      - {label: "Tags", name: "tags", widget: "list", default: "all" }
=======
      
>>>>>>> d94b9268 (Initial commit)
